@startuml

namespace minecraft {
class Minecraft
class GuiScreen
class GuiChat
class GuiIngame
}

namespace command {
class Command {
    + getCommandName()
    + getCommand()
    + getUsage()
    + printUsage()
    + printString(String msg)
    + executeCommand()
}

class CommandManager {
    + getPrefix()
    + decodeCommand()
    + getCommands()
}
}

namespace commands {
class ChangeKeybind {
    + executeCommand()
}
}

namespace gui {
namespace screens {
namespace modulegui {
class Panel {
    + drawScreen(int mouseX, int mouseY)
    + mouseClicked(int mouseX, int mouseY, int mouseButton)
    + mouseReleased(int mouseX, int mouseY, int state)
}

class PanelManager {
    + drawPanels()
    + mouseClicked()
    + mouseReleased()
}
class ModuleGui {
    + drawScreen(int mouseX, int mouseY, int partialTicks)
    + mouseClicked(int mouseX, int mouseY, int mouseButton)
    + mouseReleased(int mouseX, int mouseY, int state)
}
}

class AltLogin {
    + drawScreen(GuiScreen guiScreen)
}
}

class GuiScreenManager {
    + displayAltLogin()
    + drawScreen(GuiScreen guiScreen)
}

class HotkeyScreen {
    + getKeyCode()
}
}

namespace hud {
class HudItem {
    + renderItem()
}

namespace items {
class ModuleList {
    + renderItem()
}
}

class HudItemManager {
    + renderItems()
}
}

namespace keybinds {
class KeybindHandler {
    + onKeyPressed(int keyCode)
}
}

namespace module {
class Module {
    + getName()
    + getKeyBind()
    + setKeyBind(int keyBind)
    + getCategory()
    + getSettings()
    + onEnable()
    + onDisable()
    + onUpdate()
}

class ModuleManager {
    + getAllModules()
    + getActiveModules()
    + onUpdate()
    + getModuleByName(String module)
    + toggleModule(Module module)
    + getModulesByCategory()
    + isModuleActive(String module)
}

enum Category {
    PLAYER
    RENDER
    MOVEMENT
}
}

namespace modules {
class ChestStealer {
    + onEnable()
    + onDisable()
    + onUpdate()
}
}

namespace settings {
class Setting {
    + getActive()
    + setActive(boolean active)
    + getName()
    + handleClick(int mouseX, int mouseY)
    + draw(int x, int y)
}
}

namespace settings {
class SliderSetting {
    + handleClick()
    + draw(int x, int y)
    + getSliderVal()
}
}

namespace utils {
class MessagePrinter {
    + printMessage(String message)
}
}

Minecraft ..> ModuleManager
Minecraft ..> KeybindHandler
GuiChat ..> CommandManager
GuiIngame ..> HudItemManager
GuiScreenManager ..> "*" GuiScreen
ModuleGui ..|> HotkeyScreen
HotkeyScreen ..|> GuiScreen
AltLogin ..|> GuiScreen
ModuleManager ..> "*" Module
Module ..> Category
Module ..> "*" Setting
KeybindHandler ..> ModuleManager
KeybindHandler ..> GuiScreenManager
Panel ..> "*" Module
Panel ..> Category
ModuleGui ..> PanelManager
PanelManager ..> "*" Panel
Panel ..> ModuleManager
HudItem ..> ModuleManager
HudItemManager ..> "*" HudItem
CommandManager ..> "*" Command
Command ..> ModuleManager
Command ..> MessagePrinter
ChangeKeybind ..|> Command
ModuleList ..|> HudItem
ChestStealer ..|> Module
SliderSetting ..|> Setting

@enduml
